/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Musico.InventorySystem;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AddNewInstrument extends javax.swing.JFrame {
    
    //instance variables
    //private = access restricted
    private String priceRange = "Low";
        
    public AddNewInstrument(){
        initComponents();
        setIconImage();   // sets icon in the frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        range = new javax.swing.ButtonGroup();
        txtbrand = new javax.swing.JLabel();
        yesnobtngroup = new javax.swing.ButtonGroup();
        btnClose = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtIdNo = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtTotalItem = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        lblIdNo = new javax.swing.JLabel();
        lblRange = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblTotalItem = new javax.swing.JLabel();
        lblDIscount = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        radMedium = new javax.swing.JRadioButton();
        radHigh = new javax.swing.JRadioButton();
        radLow = new javax.swing.JRadioButton();
        radYes = new javax.swing.JRadioButton();
        radNo = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        txtbrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/textbackground.jpg"))); // NOI18N
        txtbrand.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Musico Inventory System");
        setLocation(new java.awt.Point(800, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/Close.png"))); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, -1));

        lblCategory.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblCategory.setText("Category:");
        getContentPane().add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 33));

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 220, 30));

        txtIdNo.setEditable(false);
        txtIdNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 220, 30));

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 220, 30));

        txtTotalItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalItemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, 30));

        txtBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 220, 30));

        lblIdNo.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblIdNo.setText("ID no:");
        getContentPane().add(lblIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 60, 20));

        lblRange.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblRange.setText("Range:");
        getContentPane().add(lblRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lblBrand.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblBrand.setText("Brand:");
        getContentPane().add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        lblPrice.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblPrice.setText("Price:");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        lblTotalItem.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblTotalItem.setText("Total Item:");
        getContentPane().add(lblTotalItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lblDIscount.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblDIscount.setText("Discount:");
        getContentPane().add(lblDIscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        lblItemName.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblItemName.setText("Item Name:");
        getContentPane().add(lblItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        cbCategory.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guitar", "keyboard", "Brass", "WoodWind", "Bowed ", "Nepali folk instrument" }));
        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 220, 30));

        btnAdd.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/save-icon--1.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        range.add(radMedium);
        radMedium.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        radMedium.setText("Medium");
        radMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMediumActionPerformed(evt);
            }
        });
        getContentPane().add(radMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        range.add(radHigh);
        radHigh.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        radHigh.setText("High");
        radHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHighActionPerformed(evt);
            }
        });
        getContentPane().add(radHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        range.add(radLow);
        radLow.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        radLow.setSelected(true);
        radLow.setText("Low");
        radLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLowActionPerformed(evt);
            }
        });
        getContentPane().add(radLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        yesnobtngroup.add(radYes);
        radYes.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        radYes.setText("Yes");
        radYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radYesActionPerformed(evt);
            }
        });
        getContentPane().add(radYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        yesnobtngroup.add(radNo);
        radNo.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        radNo.setSelected(true);
        radNo.setText("No");
        radNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNoActionPerformed(evt);
            }
        });
        getContentPane().add(radNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        btnClear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/cls.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 150, 30));

        lblBackground.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16)); // NOI18N
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/textbackground.jpg"))); // NOI18N
        lblBackground.setText("jLabel2");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 560, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
// closes whole program
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed

    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtIdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNoActionPerformed

    }//GEN-LAST:event_txtIdNoActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed

    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtTotalItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalItemActionPerformed

    }//GEN-LAST:event_txtTotalItemActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed

    }//GEN-LAST:event_txtBrandActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed

    }//GEN-LAST:event_cbCategoryActionPerformed
   
    // code to add items in the table
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // This method collects the data from all text fields and pass to the table of Musicoinformationlist class. 
         try {
            // Get the input value of users from the text field. 
            // .trim() removes the leading and trailing spaces in value.
            String idNo = txtIdNo.getText().trim();
            String itemName = txtItemName.getText().trim();
            String totalItem = txtTotalItem.getText().trim();
            String brand = txtBrand.getText().trim();
            String price = txtPrice.getText().trim();
            String category = cbCategory.getSelectedItem().toString();
           
            if (!idNo.isEmpty() && !itemName.isEmpty() && !totalItem.isEmpty() && !brand.isEmpty() && !price.isEmpty()){
                
                // Convert String data type to integer datatype.
                int idNumber = Integer.parseInt(idNo);
                int totalItemNo = Integer.parseInt(totalItem);
                int priceNo = Integer.parseInt(price);
                
                                                                                       
// code to add items in the table only if the fulfill the range validation             
if (priceRange == "Low"){
   // obj.setDiscount();
    if(priceNo>=1 && priceNo<=10000){
        obj.setDiscount();// method called from the YesDiscount class to get the discount percent input value.
        AppliancesInfo.addTable(idNo, itemName, totalItem, priceRange, category, brand, price, obj.disCount());
         setVisible(false);    
    }
    else{
                JOptionPane.showMessageDialog(rootPane,"For Range LOW, the price must be betweem 1-10000", "Error", JOptionPane.ERROR_MESSAGE);
           
    }
}
// FOR range MEdium
else if (priceRange == "Medium"){
    if(priceNo>=11000 && priceNo<=50000){
        obj.setDiscount();      // method called from the YesDiscount class to get the discount percent input value.
        AppliancesInfo.addTable(idNo, itemName, totalItem, priceRange, category, brand, price, obj.disCount());
                                                                                                                //Method called from YesDisocunt class.
                setVisible(false);    
    }
    else{
         JOptionPane.showMessageDialog(rootPane,"For Range Medium, the price must be between 11000 and 50000", "Error", JOptionPane.ERROR_MESSAGE);
       
    }
}
// for range High
else if (priceRange == "High"){

    if(priceNo>50000){
          obj.setDiscount();   // method called from the YesDiscount class to get the discount percent input value.
        AppliancesInfo.addTable(idNo, itemName, totalItem, priceRange, category, brand, price, obj.disCount());
                                                                                                                //Method called from YesDisocunt class.
                setVisible(false);    
    }
    else{
         JOptionPane.showMessageDialog(rootPane,"For Range High, the price must be above 50000", "Error", JOptionPane.ERROR_MESSAGE);
        
    }
} 
else {
JOptionPane.showMessageDialog(rootPane,"The price range for Low is: 1-10000"+"\nMedium: 11000-50000"+"\nHigh: Above 50000", "Error", JOptionPane.ERROR_MESSAGE);
}
            } 
            else {
                JOptionPane.showMessageDialog(rootPane,"Please fill all the text field.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException nfe){ // It is thrown when string cannot be convered to integer data type.
            JOptionPane.showMessageDialog(rootPane, "The total item and price must be numeric value.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    public void setIdNum(int id){
        // Set the text field of ID no.
        txtIdNo.setText(String.valueOf(id));
                        //Converts integer data type to String data type because Jtextfield receives only string data type.
    }
    
    private void radMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMediumActionPerformed
        priceRange = "Medium";
    }//GEN-LAST:event_radMediumActionPerformed

    private void radHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHighActionPerformed
        priceRange = "High";
    }//GEN-LAST:event_radHighActionPerformed

    private void radLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLowActionPerformed
        priceRange = "Low";
    }//GEN-LAST:event_radLowActionPerformed
    //Object of YesDiscount class.
    YesDiscount obj = new YesDiscount();

    private void radYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radYesActionPerformed
        obj.setVisible(true); // Display the YesDiscount frame.        
        obj.setDiscount();  // method called from the YesDiscount class to get the discount percent input value.
    }//GEN-LAST:event_radYesActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // Set the text field empty
        //txtIdNo.setText("");
        txtItemName.setText("");
        txtTotalItem.setText("");
        txtBrand.setText("");
        txtPrice.setText("");
        cbCategory.setSelectedIndex(0); // Set the value of 0 index in JComboBox.
        radLow.setSelected(true); // Set the default selected readion button.
        radNo.setSelected(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void radNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNoActionPerformed

    }//GEN-LAST:event_radNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewInstrument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewInstrument().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDIscount;
    private javax.swing.JLabel lblIdNo;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblTotalItem;
    private javax.swing.JRadioButton radHigh;
    private javax.swing.JRadioButton radLow;
    private javax.swing.JRadioButton radMedium;
    private javax.swing.JRadioButton radNo;
    private javax.swing.JRadioButton radYes;
    private javax.swing.ButtonGroup range;
    private javax.swing.JTextField txtBrand;
    public javax.swing.JTextField txtIdNo;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTotalItem;
    private javax.swing.JLabel txtbrand;
    private javax.swing.ButtonGroup yesnobtngroup;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("titleicon.png")));
    }
}
