/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Musico.InventorySystem;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Lenovo
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
        setIconImage(); // sets icon in the frame
        showdate();    // shows current date
        showtime();      // shows current time
    }

    void showdate() {
        Date d = new Date();
        SimpleDateFormat a = new SimpleDateFormat("dd-MM-yyyy");
        datelab.setText(a.format(d));
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat a = new SimpleDateFormat("HH:mm:ss a");
                timelab.setText(a.format(d));
            }
        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jmusicoforeveryonebtn = new javax.swing.JButton();
        jlogoutbtn = new javax.swing.JButton();
        jMusicoinformationlistbtn = new javax.swing.JButton();
        lblSystem = new javax.swing.JLabel();
        lblMusico = new javax.swing.JLabel();
        lblInventory = new javax.swing.JLabel();
        timelab = new javax.swing.JLabel();
        datelab = new javax.swing.JLabel();
        datelab1 = new javax.swing.JLabel();
        timelab1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmItemOpen = new javax.swing.JMenuItem();
        jmItemImport = new javax.swing.JMenuItem();
        jmItemExit = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jmAbout = new javax.swing.JMenuItem();
        jmDeveloper = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musico Inventory System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/icons8-information-100.png"))); // NOI18N
        jButton2.setText("Musico Information List");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 3287, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/icons8-google-web-search-100.png"))); // NOI18N
        jButton3.setText("Search By");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 3357, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/icons8-update-100.png"))); // NOI18N
        jButton4.setText("Update Musico Information List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 3439, -1, -1));

        jmusicoforeveryonebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmusicoforeveryonebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/icons8-sound-cloud-96.png"))); // NOI18N
        jmusicoforeveryonebtn.setText("\"Musico: For everyone\"");
        jmusicoforeveryonebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmusicoforeveryonebtnActionPerformed(evt);
            }
        });
        getContentPane().add(jmusicoforeveryonebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 361, 100));

        jlogoutbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlogoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/exit.png"))); // NOI18N
        jlogoutbtn.setText("Log out");
        jlogoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(jlogoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 361, 90));

        jMusicoinformationlistbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMusicoinformationlistbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/icons8-information-100.png"))); // NOI18N
        jMusicoinformationlistbtn.setText("Musico Information List");
        jMusicoinformationlistbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMusicoinformationlistbtnActionPerformed(evt);
            }
        });
        getContentPane().add(jMusicoinformationlistbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 360, 100));

        lblSystem.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setText("System");
        getContentPane().add(lblSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 330, 80));

        lblMusico.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        lblMusico.setForeground(new java.awt.Color(255, 255, 255));
        lblMusico.setText("Musico");
        getContentPane().add(lblMusico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 230, 80));

        lblInventory.setFont(new java.awt.Font("Corbel", 1, 60)); // NOI18N
        lblInventory.setForeground(new java.awt.Color(255, 255, 255));
        lblInventory.setText("Inventory");
        getContentPane().add(lblInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 330, 80));

        timelab.setBackground(new java.awt.Color(255, 255, 255));
        timelab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        timelab.setForeground(new java.awt.Color(255, 255, 255));
        timelab.setText("Time");
        getContentPane().add(timelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, 40));

        datelab.setBackground(new java.awt.Color(255, 255, 255));
        datelab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        datelab.setForeground(new java.awt.Color(255, 255, 255));
        datelab.setText("Date");
        getContentPane().add(datelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 250, 40));

        datelab1.setBackground(new java.awt.Color(255, 255, 255));
        datelab1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        datelab1.setForeground(new java.awt.Color(255, 255, 255));
        datelab1.setText("Date");
        getContentPane().add(datelab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 40));

        timelab1.setBackground(new java.awt.Color(255, 255, 255));
        timelab1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        timelab1.setForeground(new java.awt.Color(255, 255, 255));
        timelab1.setText("Time");
        getContentPane().add(timelab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Musico/InventorySystem/finalbg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1080, 690));

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jMenuBar1.setForeground(new java.awt.Color(204, 51, 0));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(68, 33000));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(60, 26));

        jMenu1.setText("File");

        jmItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmItemOpen.setText("Open file");
        jmItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jmItemOpen);

        jmItemImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmItemImport.setText("Import ");
        jmItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemImportActionPerformed(evt);
            }
        });
        jMenu1.add(jmItemImport);

        jmItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmItemExit.setText("exit");
        jmItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmItemExit);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jmAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmAbout.setText("About");
        jmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAboutActionPerformed(evt);
            }
        });
        jMenu2.add(jmAbout);

        jmDeveloper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmDeveloper.setText("Developer");
        jmDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDeveloperActionPerformed(evt);
            }
        });
        jMenu2.add(jmDeveloper);
        jMenu2.add(jSeparator2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("User help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1097, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed
// this button action even asks allows user to get into login frame from home frame
    private void jlogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutbtnActionPerformed
        int home = JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Select", JOptionPane.YES_NO_OPTION);
        if (home == 0) {
            setVisible(false);
            new MusicoInfo().setVisible(true);
        }
    }//GEN-LAST:event_jlogoutbtnActionPerformed

    // Object of AppliancesInfo
    AppliancesInfo obj = new AppliancesInfo();
    
//sets appliancesinfo frame visible
    private void jMusicoinformationlistbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMusicoinformationlistbtnActionPerformed
        obj.setVisible(true); // Display AppliancesInfo frame.  
    }//GEN-LAST:event_jMusicoinformationlistbtnActionPerformed


//sets frame that gives a glance of detail about the music shop musico
    private void jmusicoforeveryonebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmusicoforeveryonebtnActionPerformed
        new MusicoForEveryoneInformation().setVisible(true); // Display MusicoForEveryoneInformation frame.
    }//GEN-LAST:event_jmusicoforeveryonebtnActionPerformed


//opens csv file from the device
    private void jmItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemOpenActionPerformed
        // this method Opens the .csv file.
        try {
            //constructor of file class having file as argument
            File file = new File("InstrumentDetails.csv");
            Desktop desktop = Desktop.getDesktop();

            desktop.open(file);
        } catch (IllegalArgumentException ie) {  //It is thrown when the file does not exist.
            JOptionPane.showMessageDialog(rootPane, "The file does not exit.", "Error!!!", JOptionPane.ERROR_MESSAGE);

        } catch (IOException ex) { //It is thrown when there is no application associated with the given file type.
            JOptionPane.showMessageDialog(rootPane, "Error", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmItemOpenActionPerformed


// closes whole program
    private void jmItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemExitActionPerformed
        setVisible(false); // Close Home frame
    }//GEN-LAST:event_jmItemExitActionPerformed


// imports detail in the table.
    private void jmItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemImportActionPerformed
        obj.importData(); // Method called from AppliancesInfo to import data to the JTable from .csv file.
        obj.setVisible(true); // Display AppliancesInfo frame.
    }//GEN-LAST:event_jmItemImportActionPerformed


//  read  about developers in a frame from jmenuitem
    private void jmDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDeveloperActionPerformed
        new Developer().setVisible(true);
    }//GEN-LAST:event_jmDeveloperActionPerformed


// can read a litlle about the system
    private void jmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAboutActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jmAboutActionPerformed


// user can read step by step procedure to use the application. 
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new UserHelp().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelab;
    private javax.swing.JLabel datelab1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jMusicoinformationlistbtn;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton jlogoutbtn;
    private javax.swing.JMenuItem jmAbout;
    private javax.swing.JMenuItem jmDeveloper;
    private javax.swing.JMenuItem jmItemExit;
    private javax.swing.JMenuItem jmItemImport;
    private javax.swing.JMenuItem jmItemOpen;
    private javax.swing.JButton jmusicoforeveryonebtn;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblMusico;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel timelab;
    private javax.swing.JLabel timelab1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("titleicon.png")));
    }
}
